### ISSUE TITLE
[Bug] empty cycles

### ISSUE THREAD

**Issue by maxeeem** [bowen-xu/PyNARS#14]
**Describe the bug**
As I mentioned yesterday, based on my analysis of the OpenNARS codebase, whenever a concept is picked out for inference, if that concept has empty belief table like in the example of concept "bird" which is part of another concept "bird --> animal" then no inference will take place and the cycle will end early. 

In PyNARS the issue of empty cycles still exists though it is the inverse of OpenNARS. In PyNARS in GeneralEngine.py when a concept is picked, we get its term links and then take beliefs from linked concepts. So if we pick out a concept "bird --> animal", we then follow any of the term links like "bird" and get a belief from that linked concept which returns None. So once again the cycle ends early and produces no results. 

**To Reproduce**
I just put some print statements in GeneralEngine.py around line 359
            print("---")
            print("concept", concept)
            print("task", task)
            print("target", concept_target)
            print("belief", belief)
            print("---")

**Example output**
When running in the terminal, I got this output indicating the problem described above.
```
NARS: Init...
NARS: Run...
NARS: Console.
Input: <bird --> animal>.
 0.80  0.50  0.95  IN    : <bird-->animal>. %1.000;0.900%
---
concept $0.757;0.500;0.950$ <bird-->animal>
task $0.800;0.500;0.950$ <bird-->animal>. %1.000;0.900%
target $0.861;0.500;0.950$ bird
belief None
---

---
concept $0.757;0.500;0.950$ <bird-->animal>
task $0.800;0.500;0.950$ <bird-->animal>. %1.000;0.900%
target $0.861;0.500;0.950$ animal
belief None
---

Input: 1
                   INFO  : Run 1 cycles.

---
concept $0.861;0.500;0.950$ animal
task $0.800;0.500;0.950$ <bird-->animal>. %1.000;0.900%
target $0.716;0.500;0.950$ <bird-->animal>
belief $0.800;0.500;0.950$ <bird-->animal>. %1.000;0.900%
---
```

**Comment by bowen-xu** [comment]
There are some empty cycles in PyNARS. However, the same issue seems to exist in OpenNARS 3.0.4.
When `<bird --> animal>.` is input, it goes into line 127 in RuleTables.java
https://github.com/opennars/opennars/blob/4d1bdb0f599ccf6ed44edfc398f02f930713d30f/src/main/java/org/opennars/inference/RuleTables.java#L126-L127
where rule matching happens even if the beliefs-table is empty.

**Comment by maxeeem** [comment]
So if the issue is present in both, does this indicate a problem with the design or its interpretation? What should be the next steps?

**Comment by bowen-xu** [comment]
I had the same question before, but I thought it does not matter to have empty cycles. Maybe we can discuss this issue with Wang when getting a change.

**Comment by maxeeem** [comment]
When I look at the code of OpenNARS it appears to me that the issue exists not only when `<bird --> animal>.` is input but repeatedly in processing. 

@bowen-xu can you also please check my logic.

When we cycle, `selectConceptForInference` is called and say we pick out `bird --> animal`. Inside that function we call `fireConcept` which iterates through some TaskLinks and calls `fireTaskLink` for each. Inside that function we iterate through some TermLinks and call `fireTermLink` on each of them. 

It is here that the problem seems to lie since when TermLink is to a concept identified by either `bird` or `animal`, the subsequent reasoning step will _always_ produce no results since those concepts have no beliefs in their belief tables.

So it seems to me that whenever a term link is picked leading to a concept like 'bird' or 'animal' it is just wasted effort.

**Comment by maxeeem** [comment]
> However, when it comes to NAL5 (higher-order inference), it is difficult to find a more efficient way to avoid empty cycles.

can you please expand on that? How does NAL5 make it different?

**Comment by bowen-xu** [comment]
For example, in NAL1, you have sentences like
`<robin --> bird>.`, `<bird --> animal>.`
The efficient way is to take one sentence and look for another sentence according to the predicate `bird` of the former one.
There will be no empty cycles, unless there is no sentence of which `bird` is the subject.

However, in NAL5, there would be nested/recursive structures, for example, you have sentences like 
`(<{whether} --> [cloudy]> && <{ground} --> [wet]>) ==> <{whether} --> [rained_before]>.`, `<{ground} --> [wet]>.`
The previous strategy does not work. How to decide which concept to be considered at current cycle? Which two premises should be picked out for inference?

**Comment by bowen-xu** [comment]
It might not be a bug of implementation. So the issue is closed.
