### ISSUE TITLE
[Bug] Term.terms v.s. Term.sub_terms

### ISSUE THREAD

**Issue by MoonWalker1997** [bowen-xu/PyNARS#21]
**Describe the bug**
Term.terms will return (self, ), seems only one term, why it is called terms.

**Comment by bowen-xu** [comment]
I don't think this is a bug.
For `Compound`:
https://github.com/bowen-xu/PyNARS/blob/78ea9ef556385232337170f03f6568bbb2e27db0/pynars/Narsese/_py/Compound.py#L82-L84
For `Statement`:
https://github.com/bowen-xu/PyNARS/blob/78ea9ef556385232337170f03f6568bbb2e27db0/pynars/Narsese/_py/Statement.py#L62-L64
For (atomic)`Term`:
https://github.com/bowen-xu/PyNARS/blob/78ea9ef556385232337170f03f6568bbb2e27db0/pynars/Narsese/_py/Term.py#L106-L108

They have different implementations.

**Comment by bowen-xu** [comment]
`terms()` returns the terms which is the "son" of a parent for compound and statement, while return the the term itself for an atomic term.
`sub_terms()` returns all the successors of a term (as a node) as well as the term itself.

These methods are used for preprocessing of compound's components and extracting features of premises in rule matching.

**Comment by bowen-xu** [comment]
No futhur discussion, so closed.
