### ISSUE TITLE
[Bug] Improper output format for achieving goals

### ISSUE THREAD

**Issue by bowen-xu** [bowen-xu/PyNARS#26]
**Describe the bug**

When a question is solved, it displays "ANSWER":
<img width="550" alt="image" src="https://github.com/bowen-xu/PyNARS/assets/58252898/7137c3b1-8f8c-4628-8683-ebad144828b2">

When a question is solved, it also displays "ANSWER":
<img width="570" alt="image" src="https://github.com/bowen-xu/PyNARS/assets/58252898/a2b09ca1-ab4f-41d5-8c1f-adbbebdb67da">

**Expected behavior**

However, I think it should display "ACHIEVE" or "REACH".
It should only output something like
```
ACHIEVE: A. :|: %1.0;0.9%
```
without
```
ACHIEVE: A! :|: %1.0;0.9%
```

**To Reproduce**

Input in the console:
```
A! :|:
A. :|:
```

**Environment (please complete the following information):**
 - OS: MacOS 13.1
 - Language:  Python 3.8.13
 - PyNARS branch and report date (optional if the branch is master): dev 78ea9ef556385232337170f03f6568bbb2e27db0

**Comment by ARCJ137442** [comment]
By tracking the source code, I found that function "accept" in "pynars\NARS\DataStructures\_py\Memory.py" may should be extended to return a "achieved goal"  (or named as `goal_achieved`), but now I can't understand the logic in it temporary.

**Comment by ccrock4t** [comment]
see #30

**Comment by bowen-xu** [comment]
Fixed.
