### ISSUE TITLE
[Bug] Ambiguous name of `Operation` as a atomic term `^name` or statement `name(args)`

### ISSUE THREAD

**Issue by ARCJ137442** [bowen-xu/PyNARS#43]
**Describe the bug**
This issue is come from PR #37:

> According to NAL (2012):
> 
> An atomic operation is represented as an operator (a
> special term whose name starts with ‘⇑’) followed by an argument list (a
> sequence of terms, though can be empty). (P146)
> 
> an operation is a special type of event that is realizable by the system. (P150)
> 
> So I think "Operation as an atomic term" (e.g. ^op) in pynars\Narsese\_py\operation.py might need to be renamed Operator to distinguish it from "Operation as an statement". (e.g. f(x, y) or <(*, x, y) --> ^f>)

**To Reproduce**
See [`pynars/Narsese/_py/Operation.py`](https://github.com/bowen-xu/PyNARS/blob/dev/pynars/Narsese/_py/Operation.py)

**Expected behavior**
This is a conceptional issue, It only affects the development of code

**Comment by bowen-xu** [comment]
An atomic operation is represented as "an operator followed by an argument list". As I understood, `name(args)` is an atomic operation. By contrast, a compound operation is a sequential/concurrent compound of operations, like `(op1(args1), op2(args2), op3(args3))`.

**Comment by ARCJ137442** [comment]
> An atomic operation is represented as "an operator followed by an argument list". As I understood, `name(args)` is an atomic operation. By contrast, a compound operation is a sequential/concurrent compound of operations, like `(op1(args1), op2(args2), op3(args3))`.

Yeah, you're right. I understand what you say.

In Narsese, The "atomic operation" of the form "name(args)" is actually the syntactic sugar of the Narsese statement of the form "<(*, args) --> ^name>" - which is the original meaning of "an operator followed by an argument list".
But now, what I see in the class `Operation` is that it actually corresponds to "an operator" in the sentence rather than "an operator followed by an argument list".

So based on this, I think the class `Operation` in [pynars/Narsese/_py/Operation.py](https://github.com/bowen-xu/PyNARS/blob/dev/pynars/Narsese/_py/Operation.py) should be renamed `Operator` to clarify its meaning, which is exactly what you said in your reply as 'Operator'.

**Comment by bowen-xu** [comment]
That make sense. `^name` is an operator. we can change the class name in the code.

**Comment by bowen-xu** [comment]
fixed by https://github.com/bowen-xu/PyNARS/pull/46
