### ISSUE TITLE
[Bug] Redundant large HTML file affecting the "language using in PyNARS"

### ISSUE THREAD

**Issue by ARCJ137442** [bowen-xu/PyNARS#45]
**Describe the bug**
[This file](https://github.com/bowen-xu/PyNARS/blob/dev/pynars/utils/SparseLUT/temp/sparse_lut.html) is a temporary debugging file generated during the Cython compilation process, used by programmers to debug and understand the generated code, is not part of the project source code, and does not seem to be in the Github source repository.

**To Reproduce**
See [pynars/utils/SparseLUT/temp/sparse_lut.html](https://github.com/bowen-xu/PyNARS/blob/dev/pynars/utils/SparseLUT/temp/sparse_lut.html)

**Expected behavior**

The following code may needs to be added to `.gitignore`:

```.gitignore
/pynars/utils/SparseLUT/temp
```

Or:
```.gitignore
temp/
```

**Screenshots**
In [repo homepage](https://github.com/bowen-xu/PyNARS):
![image](https://github.com/bowen-xu/PyNARS/assets/61109168/579089ab-1a9d-480b-ad34-44398d8575a7)

[The 240kb large HTML file](https://github.com/bowen-xu/PyNARS/blob/dev/pynars/utils/SparseLUT/temp/sparse_lut.html) in `temp`:
![image](https://github.com/bowen-xu/PyNARS/assets/61109168/f599b7d8-c4ce-4a7a-8e7e-092b95b302ee)

**Comment by bowen-xu** [comment]
fixed. 1eff46c8ad9be6558b0e49ca0f18c6bcd86fbed9
