### ISSUE TITLE
[Bug] Backward inference

### ISSUE THREAD

**Issue by maxeeem** [bowen-xu/PyNARS#48]
**Describe the bug**
Backward inference is currently not handles correctly.

See this test case:
```
        ' Backward inference

        ' Bird is a type of swimmer.
        <bird --> swimmer>. %1.00;0.80%

        ' What is a type of swimmer?
        <?1 --> swimmer>?  

        5

        ' What is a type of bird?
        ''outputMustContain('<?1 --> bird>?')

        ' What is the type of bird?
        ''outputMustContain('<bird --> ?1>?')
```

**To Reproduce**
Type above statements in the console `python -m pynars.Console`

**Comment by bowen-xu** [comment]
I think 2 _rules_ should be added:
```
<P --> M>.
<S --> M>?
|-
<S --> P>?
```
and
```
<P --> M>.
<S --> M>?
|-
<P --> S>?
```

**Comment by maxeeem** [comment]
Will review today. Thanks!

**Comment by maxeeem** [comment]
@bowen-xu when comparing previous test run on dev with the test run on this branch, the number of failing tests is the same. This is unexpected. I'm going to investigate but my guess is that this change fixed some tests but broke other ones so the total number is ~ the same :)

<img width="1710" alt="Screenshot 2023-11-14 at 9 47 52 AM" src="https://github.com/bowen-xu/PyNARS/assets/1018034/5488c029-e880-4a48-a521-053ae0797e63">

**Comment by maxeeem** [comment]
Fixed
