### ISSUE TITLE
[Technical Report] Resource Allocation Functions

### ISSUE THREAD

**Issue by ccrock4t** [bowen-xu/PyNARS#63]
## Technical Report
>simplicity: $s = n^{−r}$ where n is the complexity, and r a system parameter
greater than zero (defaulted to 0.5).
• directness: $d = b^{-t}$ where b is the length of the evidential base and, and t
a system parameter.
• Sharpness: $2 * |e - 0.5|$.
• projectedConfidence(): $c \times (t - t' + 1)^d$, where c is the confidence, t the
current time, t′ the creationTime of the truth-value, and d a system pa-
rameter indicating the decay rate (defaulted to 1000).
• Dividing term complexity (positive integer) in budgetInference() in (Bud-
getFunctions.java) is replaced by multiplying by simplicity (real number
in (0, 1])

## More Info
We are missing the above functions which are needed to help us with resource allocation.

Simplicity (for Term), Directness, and Sharpness (for Sentences) are not mentioned in the code.

For projected confidence (for Events), a different formula is currently used (TemporalFunctions.py, `def project()`)

For the Budget Inference point, see `def Budget_inference()`

**Comment by ccrock4t** [comment]
Simplicity is added in PR #54

**Comment by ccrock4t** [comment]
The rest are added in PR #54

**Comment by ccrock4t** [comment]
You are right, its not bounded between (0,1). In [ONA ](https://github.com/opennars/OpenNARS-for-Applications/blob/7f383add0cf40851402bbfc8c04405fd1c6a5be7/src/Truth.c#L98) it is a simply decay parameter < 1 (e.g., $d=0.99$) which is applied for each timestep that has passed. i.e., $d^{(t - t')}$

**Comment by ccrock4t** [comment]
I will change it now

**Comment by ccrock4t** [comment]
I will also update the technical document

**Comment by maxeeem** [comment]
@ccrock4t @bowen-xu should we bring this up in today’s meeting?

**Comment by ccrock4t** [comment]
@maxeeem I don't think it is necessary, this is generally how we have agreed to project truth values in the past. But, it is not set in stone, meaning we can experiment with other formulas in the future (for example, Pei has suggested using a Logarithm of $t-t'$ to limit the rate of decay)

**Comment by bowen-xu** [comment]
> You are right, its not bounded between (0,1). In [ONA ](https://github.com/opennars/OpenNARS-for-Applications/blob/7f383add0cf40851402bbfc8c04405fd1c6a5be7/src/Truth.c#L98) it is a simply decay parameter < 1 (e.g., d=0.99) which is applied for each timestep that has passed. i.e., c′=c∗d(t−t′)

$c^′=c∗d^{(t−t^′)}$ looks more reasonable.

**Comment by bowen-xu** [comment]
Sorry I've been too busy recently. will review the changes asap.

**Comment by maxeeem** [comment]
I guess I’m coming from the perspective that since we’re changing the technical report, we should somehow make it explicit. This case sounds like a typo in the original report based on Bowen’s example., not just another possible formula.

**Comment by ccrock4t** [comment]
I understand/agree, but which document is the original formula from? The latest conceptual design does not mention it.
