### ISSUE TITLE
[Feature] Overall evaluation indicators for the system's internal state 

### ISSUE THREAD

**Issue by bowen-xu** [bowen-xu/PyNARS#8]
**Is your feature request related to a problem? Please describe.**

There should be some overall evaluation of the status of NARS, for example, satisfactory.

**Describe the solution you'd like**

There are four global evaluations,

- _satisfaction_: the extent to which the current situation meet the system’s desires,
- _alertness_: the extent to which the system’s knowledge is insufficient,
- _busyness_: the extent to which the system’s time resource is insufficient,
- _well-being_: the extent to which the system’s “body” functions as expected.

as mentioned in the [design report of OpenNARS 3.1.0](https://cis.temple.edu/tagit/publications/PAGI-TR-11.pdf)

The four metrics should be visualized in GUI.

**Comment by bowen-xu** [comment]
The file `pynars/NARS/GlobalEval.py` implements the four evaluations.
https://github.com/bowen-xu/PyNARS/blob/aacdb53fdd2073796e5acb8cc6e3024d490217fd/pynars/NARS/GlobalEval.py#L1-L39

This file is just to implement some methods for updating the values of S (_satisfaction_), A (_alertnss_), B (_busyness_), and W (_well-being_).

How to calculate a current evaluation depends.

For _satisfaction_, whenever a goal is to be solved, the value is updated.
Concretely, it happens in `_solev_goal()` when the system is trying to match a belief to a goal.
If there is no such a belief,
https://github.com/bowen-xu/PyNARS/blob/aacdb53fdd2073796e5acb8cc6e3024d490217fd/pynars/NARS/DataStructures/_py/Memory.py#L366
or there is a belief as a solution better than before
https://github.com/bowen-xu/PyNARS/blob/aacdb53fdd2073796e5acb8cc6e3024d490217fd/pynars/NARS/DataStructures/_py/Memory.py#L384-L384
the the value of _satisfaction_ would change.

**Comment by ccrock4t** [comment]
Closed #60 as duplicate

From #60:

## Technical Report
>• satisfaction: achieving level of a goal
>• alertness: (also known as novelty) achieving level of a task that is a judgment or a question
>• busyness: priority of a task
>• well-being: the extent a feel operator returns a value in the normal range, to be used in implementations where the system needs to manage resources other than time and space (such as energy) and its own body (such as temperature).

## More Info
The global evaluations are not implemented
